unit TestPhisicsControllerUnit;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, PhisicsControllerUnit, ControllersUnit,
  System.Generics.Collections, MenuUnit, MainUnit, Test1Unit, TestsUnit;

type
  // Test methods for class PhisicsController

  TestPhisicsController = class(TTestCase)
  strict private
    FPhisicsController: Controllers;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGetMenu; //
    procedure TestGetAnswer; //
    procedure TestGetQuest; //
    procedure TestSetTest; //
    procedure TestGetCorrect; //
  end;

implementation

procedure TestPhisicsController.TestGetQuest;
var
  ReturnValue: TList<string>;
begin
  FPhisicsController.setTest('Движение с постоянным ускорением');
  ReturnValue := FPhisicsController.GetQuest;
  CheckEquals(ReturnValue.Items[1],
    'Как определяется положение материальной точки?');
  CheckNotEquals(ReturnValue.Items[1], '+++');
  CheckEquals(ReturnValue.count, 9);
  CheckNotEquals(ReturnValue.count, 11);
end;

procedure TestPhisicsController.SetUp;
begin
  FPhisicsController := PhisicsController.Create;
end;

procedure TestPhisicsController.TearDown;
begin
  // FPhisicsController.Free;
  FPhisicsController := nil;
end;

procedure TestPhisicsController.TestGetAnswer;
var
  ReturnValue: TList<string>;
  // ReturnValue2: TList<string>;
begin
  FPhisicsController.setTest('Движение с постоянным ускорением');
  // ReturnValue2 := FPhisicsController.GetQuest;
  ReturnValue := FPhisicsController.GetAnswer;
  CheckEquals(ReturnValue.Items[1],
    'это координата, которую имеет МТ в данный момент времени');
  CheckNotEquals(ReturnValue.Items[1], '+++');
  CheckEquals(ReturnValue.Items[3],
    'это функция СКОРОСТЬ есть векторная кинематическая характеристика движения');
  CheckNotEquals(ReturnValue.Items[3], '+++');
  CheckEquals(ReturnValue.count, 10);
  CheckNotEquals(ReturnValue.count, 11);
end;

procedure TestPhisicsController.TestGetCorrect;
var
  ReturnValue: TDictionary<integer, integer>;
begin
  FPhisicsController.setTest('Движение с постоянным ускорением');
  ReturnValue:=FPhisicsController.getCorrect;
  CheckEquals(ReturnValue.Items[11], 1);
  CheckEquals(ReturnValue.Items[12], 2);
  CheckNotEquals(ReturnValue.Items[12], 12);
  CheckEquals(ReturnValue.count, 24);
end;

procedure TestPhisicsController.TestGetMenu;
var
  ReturnValue: TList<string>;
begin
  // Menu := TList<string>.Create;
  // CheckEquals (Menu.First,'Test1'); //In the test Error (should be 'test')
  // CheckNotEquals(Menu.First, 'Test2');
  // CheckEquals(Menu.Items[2], 'Test3'); // Another record type
  ReturnValue := FPhisicsController.getMenu;
  CheckEquals(ReturnValue.Items[0], 'Движение с постоянным ускорением');
  CheckNotEquals(ReturnValue.Items[0], '+++');
  CheckEquals(ReturnValue.count, 1);
end;

procedure TestPhisicsController.TestSetTest;
var
  caption: string;
  ReturnValue: TList<string>;
  // ReturnValue2: TList<string>;
begin
  // FPhisicsController.setTest('Движение с постоянным ускорением');
  caption := 'Движение с постоянным ускорением';
  FPhisicsController.setTest(caption);

  ReturnValue := FPhisicsController.GetQuest;
  CheckEquals(ReturnValue.Items[2], 'Что такое декартова система координат?');
  CheckNotEquals(ReturnValue.Items[2], '+++');
  CheckEquals(ReturnValue.Items[3],
    'Дайте определение механического движения.');
  CheckNotEquals(ReturnValue.Items[3], '+++');
  CheckNotEquals(ReturnValue.Items[2], ReturnValue.Items[3]);

end;

initialization

// Register any test cases with the test runner
RegisterTest(TestPhisicsController.Suite);

end.
