unit TestTest1Unit;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, AdaptersUnit, System.Generics.Collections, Test1Unit,
  TestsUnit,
  AccessAdapterUnit;

type
  // Test methods for class Test1

  TestTest1 = class(TTestCase)
  strict private
    Fest1: Test1;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestsetTest;
    procedure TestgetQuest;
    procedure TestgetAnswer;
    procedure TestgetCorrect;
  end;

implementation

procedure TestTest1.SetUp;
begin
  Fest1 := Test1.Create;
end;

procedure TestTest1.TearDown;
begin
  Fest1.Free;
  Fest1 := nil;
end;

procedure TestTest1.TestsetTest;
var
  caption: string;
  ReturnValue: TList<string>;
begin
  // TODO: Setup method call parameters
  caption := 'Вопросы по истории России';
  Fest1.setTest(caption);
  ReturnValue := Fest1.getQuest;
  CheckEquals(ReturnValue.Items[4],
    'Что является религиозным символом христианства?');
  CheckNotEquals(ReturnValue.Items[4], '+++');
  CheckNotEquals(ReturnValue.Items[3], ReturnValue.Items[4]);

  // TODO: Validate method results
end;

procedure TestTest1.TestgetQuest;
var
  ReturnValue: TList<string>;
begin
  Fest1.setTest('Вопросы по истории России');
  ReturnValue := Fest1.getQuest;
  CheckEquals(ReturnValue.Items[0],
    'На какой территории было создано Древнерусское государство?');
  CheckNotEquals(ReturnValue.Items[0], '+++');
  CheckEquals(ReturnValue.count, 5);
  CheckNotEquals(ReturnValue.count, 11);
  // TODO: Validate method results

end;

procedure TestTest1.TestgetAnswer;
var
  ReturnValue: TList<string>;
begin
  Fest1.setTest('Вопросы по истории России');
  ReturnValue := Fest1.getAnswer;
  CheckEquals(ReturnValue.Items[0], 'На территории современной Украины.');
  CheckNotEquals(ReturnValue.Items[0], '+++');
  CheckEquals(ReturnValue.Items[2], 'В 988–89 христианство стало государственной религией.');
  CheckNotEquals(ReturnValue.Items[2], '+++');
  CheckEquals(ReturnValue.count, 5);
  CheckNotEquals(ReturnValue.count, 10);
  // TODO: Validate method results
end;

procedure TestTest1.TestgetCorrect;
var
  ReturnValue: TDictionary<integer, integer>;
begin
  Fest1.setTest('Вопросы по истории России');
  ReturnValue := Fest1.getCorrect;
  CheckEquals(ReturnValue.Items[3], 3);
  CheckEquals(ReturnValue.Items[4], 4);
  CheckNotEquals(ReturnValue.Items[5], 15);
  CheckEquals(ReturnValue.count, 5);
  // TODO: Validate method results
end;

initialization

// Register any test cases with the test runner
RegisterTest(TestTest1.Suite);

end.
